# Generated by Django 3.1.2 on 2020-10-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestVideos',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('channel_id', models.CharField(max_length=100)),
                ('thumbnails', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoByCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latest_videos.videocategories')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latest_videos.latestvideos')),
            ],
        ),
    ]
